### ISSUE TITLE
Trouble with jspm dl-loader

### ISSUE THREAD

**Issue by derekpitt** [aurelia/event-aggregator#4]
After cloning this repo and running ```jspm dl-loader``` I get:

```
     Looking up loader files...

err  Error downloading loader files.
Potentially unhandled rejection [2] TypeError: Install of %aurelia-tools% to `^0.1.3` has no registry property provided.
    at /usr/local/lib/node_modules/jspm/lib/package.js:280:13
    at Array.forEach (native)
    at processDeps (/usr/local/lib/node_modules/jspm/lib/package.js:263:21)
    at setDefaults (/usr/local/lib/node_modules/jspm/lib/config/package.js:125:28)
    at PackageJSON.read (/usr/local/lib/node_modules/jspm/lib/config/package.js:112:3)
    at /usr/local/lib/node_modules/jspm/lib/config.js:74:25
    at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
```

Running JSPM 0.15.5
node 0.12
npm 2.5.1

**Comment by EisenbergEffect** [comment]
Please ask about this in our gitter channel. Someone there will likely be able to help you. https://gitter.im/aurelia
